"""Response Codes rules."""

from modules.seo_rules.rules.response_codes import internal_no_response  # noqa: F401
from modules.seo_rules.rules.response_codes import internal_4xx  # noqa: F401
from modules.seo_rules.rules.response_codes import internal_5xx  # noqa: F401
from modules.seo_rules.rules.response_codes import internal_redirect_loop  # noqa: F401
from modules.seo_rules.rules.response_codes import internal_redirect_self  # noqa: F401
from modules.seo_rules.rules.response_codes import internal_redirect_chain  # noqa: F401
from modules.seo_rules.rules.response_codes import internal_redirect_broken  # noqa: F401
from modules.seo_rules.rules.response_codes import internal_redirect_3xx  # noqa: F401
from modules.seo_rules.rules.response_codes import redirect_meta_refresh  # noqa: F401
from modules.seo_rules.rules.response_codes import redirect_http_refresh  # noqa: F401
from modules.seo_rules.rules.response_codes import redirect_javascript  # noqa: F401
from modules.seo_rules.rules.response_codes import redirect_trailing_slash_mismatch  # noqa: F401
from modules.seo_rules.rules.response_codes import redirect_case_normalization  # noqa: F401
from modules.seo_rules.rules.response_codes import internal_blocked_by_robots  # noqa: F401
from modules.seo_rules.rules.response_codes import internal_blocked_resource  # noqa: F401
from modules.seo_rules.rules.response_codes import external_blocked_resource  # noqa: F401
from modules.seo_rules.rules.response_codes import external_no_response  # noqa: F401
from modules.seo_rules.rules.response_codes import external_4xx  # noqa: F401
from modules.seo_rules.rules.response_codes import external_5xx  # noqa: F401
from modules.seo_rules.rules.response_codes import external_redirect_broken  # noqa: F401
from modules.seo_rules.rules.response_codes import external_redirected  # noqa: F401
from modules.seo_rules.rules.response_codes import resource_redirect_broken  # noqa: F401
from modules.seo_rules.rules.response_codes import resource_redirect_self  # noqa: F401
from modules.seo_rules.rules.response_codes import resource_redirect_chain_loop  # noqa: F401
from modules.seo_rules.rules.response_codes import resource_redirected  # noqa: F401
from modules.seo_rules.rules.response_codes import broken_internal_url  # noqa: F401
from modules.seo_rules.rules.response_codes import url_resolves_http_and_https  # noqa: F401
